#############################################
#  Initial Makefile - devops/container/cm
#############################################
IMAGE_NAME=common-brm-config_jobs
IMAGE_TAG=common-config-jobs-R5.1.21-070323
# include the common routines
include  /home/devops/brm_sdk/tab-devops-tools/buildfiles/makefile.common
