#############################################
#  Initial Makefile - devops/container/cm
#############################################
IMAGE_NAME=common-brmapps
IMAGE_TAG=common-brm-apps-R5.1.21-070323

# include the common routines
include  /home/devops/brm_sdk/tab-devops-tools/buildfiles/makefile.common
