#############################################
#  Initial Makefile - devops/container/cm
#############################################
IMAGE_NAME=common-brm-cm
IMAGE_TAG=common-cm-R5.1.21-070323
# include the common routines
include /home/devops/brm_sdk/tab-devops-tools/buildfiles/makefile.common
